# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "849972fb7fe901896f265719f52f04d9cb0afe79";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "849972fb7fe901896f265719f52f04d9cb0afe79";
      fetchSubmodules = false;
      sha256 = "sha256-SfiFXIvDp0f8akK3lppd6cGuPLcnk9dVcMqK8Jl/0Fk=";
    };
    date = "2024-08-28";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "9f42edc9d5ada43962fe65d3a2ed6db21763641a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "9f42edc9d5ada43962fe65d3a2ed6db21763641a";
      fetchSubmodules = false;
      sha256 = "sha256-KbkXEDhv1MTj51/3e7EQEy9JCQ0mbbKu84hufVXmoEk=";
    };
    date = "2024-08-12";
  };
}
